# Generated by Django 3.2.9 on 2021-12-02 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_and_number', models.CharField(max_length=10)),
                ('Telephone', models.CharField(max_length=11)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Otchestvo', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(default=0)),
                ('Employment_contract', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telephone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Otchestvo', models.CharField(max_length=50)),
                ('Access_rights', models.BooleanField(default=0)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(default='', max_length=300)),
                ('ID_Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavelapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Design', models.CharField(max_length=50)),
                ('Comments', models.CharField(max_length=50)),
                ('Cost', models.IntegerField(default=0)),
                ('Time', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=20)),
                ('ID_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavelapp.customer')),
            ],
        ),
    ]
