# Generated by Django 3.2.9 on 2021-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
